# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  docker:
    - image: circleci/node:8

jobs:
  build:
    <<: *defaults 
    steps:
      - checkout

      - run: sudo npm i -g npm

      - run: cd developer-hub-ui && npm ci

      - run: cd developer-hub-ui && npm run build

      - run: cd tquinlan92-material-core-ui-demo && npm ci

      - run: cd tquinlan92-material-core-ui-demo && npm run build

  deployTquinla92TypescriptReduxUtils:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > tquinlan92-typescript-redux-utils/.npmrc
      - run:
          name: Publish package
          command: cd tquinlan92-typescript-redux-utils && npm publish
  deployDeveloperHubHeadless:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > developer-hub-headless/.npmrc
      - run:
          name: Publish package
          command: cd developer-hub-headless && npm publish
  deployTquinlan92MaterialCoreUi:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > tquinlan92-material-core-ui/.npmrc
      - run:
          name: Publish package
          command: cd tquinlan92-material-core-ui && npm publish

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deployTquinla92TypescriptReduxUtils:
          filters: 
            branches:
              only: 
                - master
            tags:
              only: /-tquinlan92$/
          requires: 
            - build
      - deployDeveloperHubHeadless:
          filters: 
            branches:
              only: 
                - master
            tags:
              only: /-developerHubHeadless$/
          requires: 
            - build
      - deployTquinlan92MaterialCoreUi:
          filters: 
            branches:
              only: 
                - tquinlan92-react-components
          requires: 
            - build
