# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  docker:
    - image: circleci/node:8

jobs:
  build:
    <<: *defaults 
    steps:
      - checkout

      - run: sudo npm i -g npm

      - run: cd developer-hub-ui && npm ci && npm run build

      - run: cd tquinlan92-material-core-ui && npm ci && npm run build && npm test

      - run: cd tquinlan92-material-core-ui-demo && npm ci && npm run build && npm test

  deployTquinla92TypescriptReduxUtils:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Publish tquinlan92-typescript-redux-utils
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > tquinlan92-material-core-ui/.npmrc
              cd tquinlan92-typescript-redux-utils && npm publish
            fi
  deployDeveloperHubHeadless:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Publish developer-hub-headless
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > tquinlan92-material-core-ui/.npmrc
              cd developer-hub-headless && npm publish
            fi
  deployTquinlan92MaterialCoreUi:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Publish tquinlan92-material-core-ui
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > tquinlan92-material-core-ui/.npmrc
              cd tquinlan92-material-core-ui && npm publish
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deployTquinla92TypescriptReduxUtils:
          filters: 
            branches:
              ignore: /.*/
            tags:
              only: /-Tquinla92TypescriptReduxUtils$/
          requires: 
            - build
      - deployDeveloperHubHeadless:
          filters: 
            branches:
              only: master
            tags:
              only: /-developerHubHeadless$/
          requires: 
            - build
      - deployTquinlan92MaterialCoreUi:
          filters: 
            branches:
              ignore: /.*/
            tags:
              only: /-Tquinlan92MaterialCoreUi$/
          requires: 
            - build
