# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: sudo npm i -g npm

      - run: cd tquinlan92-typescript-redux-utils && npm install
      - run: cd tquinlan92-typescript-redux-utils && npm run build

      - run: cd core && npm install
      - run: cd core && npm run build

      - run: cd developer-hub-ui && npm install
      - run: cd developer-hub-ui && npm run build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

